name: HDMI
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.12
  - pandas=1.3.5
  - numpy=1.21.6
  - biopython=1.81
  - pysam>=0.19.0
  - blast>=2.12.0
  - bowtie2=2.5.4
  - samtools=1.20
  - pip
