name: HDMI
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.7
  - pandas>=1.3.0
  - numpy>=1.21.0
  - biopython>=1.79
  - pysam>=0.19.0
  - blast>=2.12.0
  - bowtie2>=2.4.0
  - samtools>=1.12
  - pip
